function y = matlab_vawt_sil_hour_step_vector(u)
%MATLAB_VAWT_SIL_HOUR_STEP_VECTOR Vector wrapper for Simulink MATLAB Fcn blocks.

[ ...
    omegaNext, ...
    tsrMean, ...
    cpMean, ...
    aeroTorqueMeanNm, ...
    generatorTorqueMeanNm, ...
    brakeTorqueMeanNm, ...
    electricalPowerMeanKw, ...
    modeId, ...
    tsrErrorIntegralNext, ...
    lastTorqueNext] = matlab_vawt_sil_hour_step(u(1), u(2), u(3), u(4), u(5));

y = [
    omegaNext;
    tsrMean;
    cpMean;
    aeroTorqueMeanNm;
    generatorTorqueMeanNm;
    brakeTorqueMeanNm;
    electricalPowerMeanKw;
    modeId;
    tsrErrorIntegralNext;
    lastTorqueNext;
];

end
